module.exports = {
  serverError: 'Internal Server Error',
  somethingWentWrong: 'Something Went Wrong, Please Try Again',
  notFoundError: 'Method Or URL Not Found',
  validationErrors: 'Validation Error',
  invalidJson: 'Invalid JSON Format',
  tooManyRequests: 'Too Many Requests',
  permissionDenied: 'Permission Denied',
  unauthorized: 'Unauthorized',
  fileNotFound: 'File Not Found',
  jwt: {
    issued: 'Token Issued Successfully',
    invalidAuthorization: 'Invalid Authorization',
    invalidToken: 'Invalid Token',
    tokenExpired: 'Token Expired',
  },
  auth: {
    passwordWrong: 'Password Is Wrong',
    loggedIn: 'Logged In Successfully',
    loggedOut: 'Logged Out Successfully',
  },
  user: {
    data: 'User Data',
    created: 'User Created Successfully',
    blocked: 'User Blocked',
    unblocked: 'User Unblocked Successfully',
    exists: 'User Already Exists',
    notFound: 'User Not Found',
    invalid: 'Invalid User',
    emailExists: 'User With Email Already Exists',
    phoneExists: 'User With Phone Already Exists',
  },
};
